{% set name = "pytest-localserver" %}
{% set version = "0.5.1.post0" %}
{% set hash = "5ec7f8e6534cf03887af2cb59e577f169ac0e8b2fd2c3e3409280035f386d407" %}
{% set ext = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ ext }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python 2.7|>=3.3
    - setuptools
    - pip
  run:
    - python 2.7|>=3.3
    - werkzeug >=0.10

test:
  requires:
    - pytest
  imports:
    - pytest_localserver
  commands:
    - py.test --help

about:
  home: https://github.com/pytest-dev/pytest-localserver
  license: MIT
  license_file: LICENSE
  summary: pytest-localserver is a plugin for the pytest testing framework which enables you to test server connections locally.

extra:
  recipe-maintainers:
    - nicoddemus
