{% set name = "pytest-localserver" %}
{% set version = "0.6.0" %}
{% set hash = "ddc479aba96a7da0e7a1cc7d3a303e50582d6d505803e8f67b827218f9fe0f65" %}
{% set ext = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ ext }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
  run:
    - aiosmtpd
    - python >=3.5    
    - werkzeug >=0.10

test:
  requires:
    - pytest
  imports:
    - pytest_localserver
  commands:
    - pytest --help

about:
  home: https://github.com/pytest-dev/pytest-localserver
  license: MIT
  license_file: LICENSE
  summary: pytest-localserver is a plugin for the pytest testing framework which enables you to test server connections locally.

extra:
  recipe-maintainers:
    - nicoddemus
